twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/css/email': email
